Repository openshift/community.okd, pull requests merged in 2020-10, with the labels that each got.

#40 Add openshift_route module for route creation
  molecule/default/tasks/openshift_route.yml
  molecule/default/verify.yml
  plugins/modules/openshift_route.py
Labels: approved, lgtm

#46 Fixes #45 with correct version_added in openshift_route
  plugins/modules/openshift_route.py
Labels: approved, has_issue, lgtm, priority/low, type/documentation

#44 Add openshift_process module
  molecule/default/files/example.env
  molecule/default/files/nginx.env
  molecule/default/files/simple-template.yaml
  molecule/default/tasks/openshift_process.yml
  molecule/default/verify.yml
  plugins/modules/openshift_process.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: approved, lgtm, priority/high

#47 Added openshift_process and openshiift_route to the README page
  README.md
Labels: approved, type/documentation

#49 Fixes #48: Update CHANGELOG and set up release 0.3.0.
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/40-openshift_route.yml
  changelogs/fragments/44-openshift_process.yml
  ci/downstream.sh
  galaxy.yml
Labels: approved, lgtm
