Repository openshift/community.okd, pull requests merged in 2020-09, with the labels that each got.

#20 add downstream build scripts
  .github/workflows/ansible-test.yml
  Makefile
  ci/downstream.sh
  ci/incluster_integration_downstream.sh
  ci/incluster_integration_upstream.sh
Labels: approved, lgtm

#26 Fixes #24: Update CHANGELOG in preparation for release 0.1.0.
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/1-initial-content.yml
  changelogs/fragments/11-dockerfile-tests.yml
  changelogs/fragments/12-dockerfile-tests.yml
  changelogs/fragments/13-makefile-tests.yml
  changelogs/fragments/15-ci-documentation.yml
  changelogs/fragments/16-inventory-plugin-tests.yml
  changelogs/fragments/18-openshift-connection-plugin.yml
  changelogs/fragments/20-downstream-build-scripts.yml
  changelogs/fragments/7-molecule-tests.yml
  changelogs/fragments/8-stale-bot.yml
Labels: approved, lgtm

#27 Route API Group
  plugins/inventory/openshift.py
Labels: approved, lgtm, ok-to-test

#23 combine incluster-integration and separate regular integration scripts
  .github/workflows/ansible-test.yml
  Makefile
  ci/downstream.sh
  ci/incluster_integration.sh
  ci/incluster_integration_downstream.sh
Labels: approved, lgtm

#29 Don't update image field when we can't manage it
  ci/downstream.sh
  ci/incluster_integration.sh
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/vars/main.yml
  plugins/modules/k8s.py
Labels: approved, lgtm

#33 Move k8s_auth library from community.kubernetes to openshift_auth
  molecule/default/prepare.yml
  molecule/default/tasks/openshift_auth.yml
  molecule/default/verify.yml
  plugins/modules/k8s.py
  plugins/modules/k8s_auth.py
  plugins/modules/openshift_auth.py
Labels: approved, lgtm

#37 Fixes #36: Add contribution guide.
  CONTRIBUTING.md
  README.md
  ci/Dockerfile
Labels: approved, lgtm, type/documentation

#39 Prepare to publish 0.2.0 release to Galaxy
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/27-route-api-group.yml
  changelogs/fragments/33-add-k8s_auth.yml
  changelogs/fragments/36-contribution-guide.yml
  galaxy.yml
  plugins/modules/openshift_auth.py
Labels: approved, lgtm
