Repository openshift/community.okd, pull requests merged in 2021-02, with the labels that each got.

#67 Fix doc string
  plugins/modules/k8s.py
Labels: lgtm

#68 Remove has_action field from doc fragment
  ci/downstream_fragments.py
Labels: approved, lgtm

#66 Restrict kubernetes.core dependency version
  changelogs/fragments/66-restrict-kubernetes-core-version.yaml
  galaxy.yml
Labels: approved

#70 Prepare for 1.0.2 release
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  ci/downstream.sh
  galaxy.yml
Labels: approved, lgtm

#69 typo: conig -> config
  plugins/connection/oc.py
Labels: approved, lgtm, needs-ok-to-test

#71 Increase kubernetes.core dependency version number
  changelogs/fragments/71-bump-kubernetes-core-version.yaml
  galaxy.yml
Labels: approved, lgtm

#72 Release version 1.1.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  ci/downstream.sh
  galaxy.yml
Labels: approved, lgtm
