Repository openshift/community.okd, pull requests merged in 2021-09, with the labels that each got.

#104 Add turbo mode docs
  README.md
  docs/ansible_turbo_mode.rst
Labels: approved, lgtm

#108 Replace IMAGE_FORMAT env var
  ci/incluster_integration.sh
Labels: approved

#107 Fix sanity test errors
  plugins/modules/openshift_route.py
  test-requirements.txt
Labels: approved, lgtm

#110 shellcheck: SC2236: Use -n instead of ! -z.
  ci/incluster_integration.sh
Labels: approved, lgtm

#114 gitignore ansible collections dir is used by the Makefile
  .gitignore
Labels: approved, lgtm

#111 Update README
  README.md
Labels: lgtm

#118 pylint: ignore a use-a-generator message
  plugins/modules/k8s.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: approved, lgtm

#117 improve turbo mode support
  plugins/module_utils/k8s.py
  plugins/module_utils/openshift_process.py
  plugins/modules/k8s.py
  plugins/modules/openshift_process.py
  tests/sanity/ignore-2.10.txt
  tests/sanity/ignore-2.11.txt
  tests/sanity/ignore-2.9.txt
Labels: approved, lgtm

#119 Copy ignore-2.12.txt to ignore-2.13.txt
  changelogs/fragments/0-copy_ignore_txt.yml
  tests/sanity/ignore-2.13.txt
Labels: approved, ok-to-test, lgtm
