Repository openshift/community.okd, pull requests merged in 2023-11, with the labels that each got.

#197 Update owners file
  OWNERS_ALIASES
Labels: approved, lgtm, needs-ok-to-test

#205 Relax the python version in downstream build
  ci/downstream.sh
Labels: approved, lgtm

#206 Prepare release 3.0.0
  CHANGELOG.rst
  Makefile
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/20230206-deprecate-openshift-inventory.yml
  changelogs/fragments/20231107-move-sanity-and-units-to-gha.yml
  ci/downstream.sh
  docs/community.okd.k8s_module.rst
  docs/community.okd.oc_connection.rst
  docs/community.okd.openshift_adm_groups_sync_module.rst
  docs/community.okd.openshift_adm_migrate_template_instances_module.rst
  docs/community.okd.openshift_adm_prune_auth_module.rst
  docs/community.okd.openshift_adm_prune_builds_module.rst
  docs/community.okd.openshift_adm_prune_deployments_module.rst
  docs/community.okd.openshift_adm_prune_images_module.rst
  docs/community.okd.openshift_auth_module.rst
  docs/community.okd.openshift_import_image_module.rst
  docs/community.okd.openshift_inventory.rst
  docs/community.okd.openshift_process_module.rst
  docs/community.okd.openshift_registry_info_module.rst
  docs/community.okd.openshift_route_module.rst
  galaxy.yml
  requirements.yml
Labels: approved, ok-to-test, lgtm

#209 [backport/stable-3] Add .gitignore to downstream build files (#208)
  ci/downstream.sh
Labels: approved, lgtm
